name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed
  $CHANGES
categories:
  - title: ':boom: Breaking Changes'
    label: 'breaking change'
  - title: ':rocket: New Features'
    label: 'new feature'
  - title: ':bug: Bug Fixes'
    label: 'fix'
  - title: ':sparkles: Enhancement'
    label: 'enhancement'
  - title: ':wrench: Maintenance'
    label: 'maintenance'
  - title: ':book: Documentation'
    label: 'documentation'
  - title: ':shield: Security'
    label: 'security fix'
  - title: ':gear: Dependency Updates'
    label: 'dependencies'
  - title: ':apple: @compositionjs/core Updates'
    label: '@compositionjs/core'

version-resolver:
  major:
    labels:
      - 'breaking change'
  minor:
    labels:
      - 'new feature'
      - 'enhancement'
  patch:
    labels:
      - 'fix'
      - 'maintenance'
      - 'documentation'
      - 'dependencies'
      - 'security'

exclude-labels:
  - 'skip-changelog'
